import * as fs from 'fs';
import * as path from 'path';
import { Injectable } from '@nestjs/common';
import { HeroService } from '../hero/hero.service';
import { HeroMetaService } from '../hero-meta/hero-meta.service';
import { CUSTOM_TAG_DEFINITIONS } from 'shared';
import type { HeroEvaluationValues } from 'shared';

// Testing-only surface (Blueprint/11-operational-notes.md, "Testing-only
// calibration UI"). Assembles, per hero, everything needed to eyeball the
// calibration in one table: raw axis values, which custom tags carry them,
// real OpenDota winRate, and the model's own favoured-rate under three
// configurations.
//
// Registered only outside production (app.module.ts) — this exposes the whole
// internal calibration surface and has no place in a shipped build.

// Three datasets rather than a single before/after, because there are two
// independent things layered on top of the raw model and it's useful to see
// each in isolation:
//   noTags    — honest model, hand-authored tag layer off entirely
//   tags      — tag layer on, still no real-winRate blending
//   tagsBlend — production: tags on AND real winRate blended in
// Difference between the first two is what the tags do; between the last two
// is how much of the number is just reality being mixed back in.
export const DEBUG_DATASETS = [
  { key: 'noTags', file: 'debug-ds-no-tags.json', label: 'no tags · no real-WR blend' },
  { key: 'tags', file: 'debug-ds-tags.json', label: 'tags on · no real-WR blend' },
  { key: 'tagsBlend', file: 'debug-ds-tags-blend.json', label: 'tags on · real-WR blend (production)' },
] as const;

export type DebugDatasetKey = (typeof DEBUG_DATASETS)[number]['key'];

export interface HeroDebugRow {
  heroId: number;
  name: string;
  primaryAttribute: string;
  axes: HeroEvaluationValues;
  tags: { name: string; hidden: boolean }[];
  realWinRate: number | null;
  // Keyed by DEBUG_DATASETS[].key; null when that dataset hasn't been
  // generated — the page renders the gap rather than pretending.
  ourWinRate: Record<string, number | null>;
  divergence: Record<string, number | null>;
}

export interface DebugDatasetInfo {
  key: string;
  label: string;
  path: string;
  present: boolean;
  generatedAt: string | null;
  config: Record<string, unknown> | null;
}

export interface HeroDebugMatrix {
  rows: HeroDebugRow[];
  datasets: DebugDatasetInfo[];
}

const DATA_DIR = path.join(__dirname, '..', '..', 'data');

interface DatasetFile {
  generatedAt?: string;
  config?: Record<string, unknown>;
  heroTable?: { heroId: number; favoredRate: number }[];
}

function readDataset(file: string): {
  generatedAt: string | null;
  config: Record<string, unknown> | null;
  byHeroId: Map<number, number>;
} {
  const full = path.join(DATA_DIR, file);
  if (!fs.existsSync(full)) return { generatedAt: null, config: null, byHeroId: new Map() };
  const parsed = JSON.parse(fs.readFileSync(full, 'utf-8')) as DatasetFile;
  return {
    generatedAt: parsed.generatedAt ?? null,
    config: parsed.config ?? null,
    byHeroId: new Map((parsed.heroTable ?? []).map((h) => [h.heroId, h.favoredRate])),
  };
}

@Injectable()
export class DevService {
  constructor(
    private readonly heroService: HeroService,
    private readonly heroMeta: HeroMetaService,
  ) {}

  async heroMatrix(): Promise<HeroDebugMatrix> {
    const heroes = await this.heroService.findAll();

    // Read on every request rather than caching in the constructor: these
    // files are regenerated by build-debug-matrix while the dev server is
    // running, and a cached copy would quietly serve the previous run.
    const loaded = DEBUG_DATASETS.map((d) => ({ ...d, ...readDataset(d.file) }));

    const tagsByHero = new Map<string, { name: string; hidden: boolean }[]>();
    for (const def of CUSTOM_TAG_DEFINITIONS) {
      for (const heroName of def.heroNames) {
        const list = tagsByHero.get(heroName) ?? [];
        // "hidden" here means never rendered to a player on a card — a tag
        // that is neither always-visible nor revealable.
        list.push({ name: def.name, hidden: !def.visible && !def.revealable });
        tagsByHero.set(heroName, list);
      }
    }

    const rows: HeroDebugRow[] = heroes.map((hero) => {
      const real = this.heroMeta.getWinRate(hero.id);
      const ourWinRate: Record<string, number | null> = {};
      const divergence: Record<string, number | null> = {};
      for (const d of loaded) {
        const ours = d.byHeroId.get(hero.id) ?? null;
        ourWinRate[d.key] = ours;
        divergence[d.key] = real === null || ours === null ? null : ours - real;
      }
      return {
        heroId: hero.id,
        name: hero.name,
        primaryAttribute: hero.primary_attribute,
        axes: hero.evaluation_values,
        tags: tagsByHero.get(hero.name) ?? [],
        realWinRate: real,
        ourWinRate,
        divergence,
      };
    });

    return {
      rows,
      datasets: loaded.map((d) => ({
        key: d.key,
        label: d.label,
        path: `server/data/${d.file}`,
        present: d.byHeroId.size > 0,
        generatedAt: d.generatedAt,
        config: d.config,
      })),
    };
  }
}
